<script setup lang="ts">
import { computed, reactive, ref, watch } from "vue";
import { Copy, Plus, Search, TicketCheck, XCircle } from "lucide-vue-next";
import AdminPageHeader from "@/components/admin/AdminPageHeader.vue";
import AdminDataTable from "@/components/admin/AdminDataTable.vue";
import FilterBar from "@/components/admin/FilterBar.vue";
import StatusBadge from "@/components/admin/StatusBadge.vue";
import { api } from "@/lib/api";
import { formatDate } from "@/lib/format";

interface Invite { code: string; kind: string; days: number; status: string; used_by_tg: number | null; used_by_account_id: string | null; expires_at: string | null; used_at: string | null }
const items = ref<Invite[]>([]); const total = ref(0); const loading = ref(true); const search = ref(""); const status = ref(""); const generated = ref<Invite[]>([]); const notice = ref(""); const error = ref(""); let timer: number | undefined;
const form = reactive({ kind: "registration", days: 30, count: 1, expires_at: "" });
const canShowDays = computed(() => form.kind !== "whitelist");
function tone(value: string): "success"|"warning"|"danger"|"muted" { return value === "active" ? "success" : value === "used" ? "muted" : value === "expired" ? "warning" : "danger"; }
async function load(){loading.value=true;const params=new URLSearchParams({limit:"100",offset:"0"});if(search.value)params.set("search",search.value);if(status.value)params.set("status",status.value);try{const result=await api<{items:Invite[];total:number}>(`/admin/invitation-codes?${params}`);items.value=result.items;total.value=result.total;}finally{loading.value=false;}}
async function generate(){error.value="";try{const result=await api<{items:Invite[]}>("/admin/invitation-codes",{method:"POST",body:JSON.stringify({...form,days:canShowDays.value?form.days:0,expires_at:form.expires_at?new Date(form.expires_at).toISOString():null})});generated.value=result.items;notice.value=`已生成 ${result.items.length} 个邀请码`;await load();}catch(reason){error.value=reason instanceof Error?reason.message:"生成失败";}}
async function revoke(item:Invite){await api(`/admin/invitation-codes/${encodeURIComponent(item.code)}/revoke`,{method:"POST",body:"{}"});await load();}
async function copy(value:string){await navigator.clipboard.writeText(value);notice.value="邀请码已复制";}
async function copyAll(){await navigator.clipboard.writeText(generated.value.map((item)=>item.code).join("\n"));notice.value="本批邀请码已全部复制";}
watch([search,status],()=>{window.clearTimeout(timer);timer=window.setTimeout(load,300)});load();
</script>
<template><div class="page-stack"><AdminPageHeader eyebrow="INVITATION CENTER" title="邀请码中心" description="Web 与 Telegram 使用相同格式和同一核销记录，可批量生成、复制、追踪和作废。" :icon="TicketCheck"><template #meta><span class="date-chip">共 {{ total }} 个邀请码</span></template></AdminPageHeader><div v-if="notice" class="success-banner">{{ notice }}</div><div v-if="error" class="error-banner">{{ error }}</div>
<section class="invite-layout"><form class="panel invite-form" @submit.prevent="generate"><div class="panel-heading"><Plus :size="19"/><div><span class="section-kicker">GENERATE</span><h2>生成邀请码</h2></div></div><label><span>类型</span><select v-model="form.kind"><option value="registration">注册邀请码</option><option value="renewal">续期码</option><option value="whitelist">白名单码</option></select></label><label v-if="canShowDays"><span>账号有效天数</span><input v-model.number="form.days" type="number" min="1" max="3650" required/></label><label><span>生成数量</span><input v-model.number="form.count" type="number" min="1" max="500" required/></label><label><span>邀请码自身过期时间</span><input v-model="form.expires_at" type="datetime-local"/><small>留空时使用系统设置中的默认有效期。</small></label><button class="primary-button"><Plus :size="16"/> 生成邀请码</button></form><section v-if="generated.length" class="panel generated-card"><header><div><span class="section-kicker">JUST GENERATED</span><h2>本批生成结果</h2></div><button class="secondary-button" @click="copyAll"><Copy :size="15"/> 全部复制</button></header><button v-for="item in generated" :key="item.code" class="generated-code" @click="copy(item.code)"><code>{{ item.code }}</code><Copy :size="14"/></button></section></section>
<section class="panel table-panel"><FilterBar><label class="search-box"><Search :size="18"/><input v-model.trim="search" placeholder="搜索邀请码"/></label><label class="select-box"><select v-model="status"><option value="">全部状态</option><option value="unused">可使用</option><option value="used">已使用</option><option value="expired">已过期</option><option value="revoked">已作废</option></select></label></FilterBar><AdminDataTable :loading="loading" :empty="!items.length" empty-title="暂无邀请码" min-width="900px"><template #head><tr><th>邀请码</th><th>类型</th><th>账号天数</th><th>过期时间</th><th>使用者</th><th>状态</th><th/></tr></template><template #body><tr v-for="item in items" :key="item.code"><td><button class="code-copy" @click="copy(item.code)"><code>{{ item.code }}</code><Copy :size="13"/></button></td><td>{{ item.kind }}</td><td>{{ item.kind==='whitelist'?'—':`${item.days} 天` }}</td><td>{{ formatDate(item.expires_at,"永不过期") }}</td><td>{{ item.used_by_tg && item.used_by_tg > 0 ? `TG ${item.used_by_tg}` : item.used_by_account_id ? `账号 ${item.used_by_account_id.slice(0,8)}` : "—" }}</td><td><StatusBadge :label="item.status" :tone="tone(item.status)"/></td><td><button v-if="item.status==='active'" class="text-button negative-text" @click="revoke(item)"><XCircle :size="14"/> 作废</button></td></tr></template></AdminDataTable></section></div></template>
<style scoped>.invite-layout{display:grid;grid-template-columns:minmax(300px,.7fr) minmax(400px,1.3fr);gap:17px}.invite-form{display:grid;gap:14px;padding:22px}.invite-form label{display:grid;gap:7px}.invite-form input,.invite-form select{padding:10px 12px;color:var(--text);border:1px solid var(--border);border-radius:10px;background:rgba(255,255,255,.035)}.generated-card{padding:22px}.generated-card header{display:flex;justify-content:space-between;align-items:center;margin-bottom:13px}.generated-code,.code-copy{display:flex;align-items:center;justify-content:space-between;gap:10px;width:100%;padding:9px 10px;color:var(--text);border:1px solid var(--border);border-radius:9px;background:rgba(255,255,255,.025);cursor:pointer}.generated-code+.generated-code{margin-top:7px}.code-copy{width:auto;border:0;background:transparent}@media(max-width:850px){.invite-layout{grid-template-columns:1fr}}</style>
