import type { OperationId } from './generated/client'

export type Dataset = { label: string; operation: OperationId; query?: Record<string, string | number>; permission?: string }
export type ActionField = { key: string; label: string; type?: 'text' | 'number' | 'textarea' | 'json' | 'select' | 'checkbox'; placeholder?: string; options?: { label: string; value: string }[]; required?: boolean; path?: boolean }
export type PageAction = { label: string; title: string; operation: OperationId; permission?: string; fields: ActionField[]; defaults?: Record<string, unknown>; idempotent?: boolean }

export const datasets: Record<string, Dataset[]> = {
  '/emby': [{ label: '已绑定账号', operation: 'listMyEmbyBindings' }],
  '/wallet': [{ label: '充值订单', operation: 'listMyRechargeOrders' }, { label: '积分账本', operation: 'listMyLedger' }, { label: '充值商品', operation: 'listPublicRechargeProducts' }, { label: '会员商品', operation: 'listPublicMembershipProducts' }],
  '/playback': [{ label: '播放历史', operation: 'listMyPlaybackHistory' }, { label: '在线播放', operation: 'listMyOnlinePlayback' }],
  '/devices': [{ label: '我的设备', operation: 'listMyDevices' }],
  '/tickets': [{ label: '我的工单', operation: 'listMyTickets' }],
  '/reviews': [{ label: '我的影评', operation: 'listMyReviews' }, { label: '社区影评', operation: 'listPublicReviews' }],
  '/notifications': [{ label: '消息', operation: 'listMyNotifications' }, { label: '通知偏好', operation: 'listNotificationPreferences' }],
  '/account': [{ label: '账号资料', operation: 'getCurrentAccount' }],
  '/admin/accounts': [{ label: '统一账号', operation: 'listAccounts' }, { label: '账号标签', operation: 'listAccountTags' }],
  '/admin/memberships': [{ label: '会员方案', operation: 'listMembershipPlans' }, { label: '邀请码', operation: 'listInvitations' }, { label: '会员商品', operation: 'listAllMembershipProducts' }],
  '/admin/emby': [{ label: 'Emby 实例', operation: 'listEmbyInstances' }, { label: '同步任务', operation: 'listEmbyTasks' }, { label: '远端账号', operation: 'listImportedEmbyUsers' }, { label: '账号绑定', operation: 'listEmbyBindings' }],
  '/admin/commerce': [{ label: '充值订单', operation: 'listRechargeOrders' }, { label: '退款', operation: 'listRechargeRefunds' }, { label: '充值商品', operation: 'listAllRechargeProducts' }, { label: '会员商品', operation: 'listAllMembershipProducts' }],
  '/admin/batches': [{ label: '批量任务', operation: 'listBatchOperations' }, { label: '账号标签', operation: 'listAccountTags' }],
  '/admin/playback': [{ label: '在线播放', operation: 'listOnlinePlayback' }, { label: '播放历史', operation: 'listPlaybackHistory' }, { label: '设备画像', operation: 'listDeviceProfiles' }, { label: '设备规则', operation: 'listDeviceRules' }],
  '/admin/risk': [{ label: '风险事件', operation: 'listRiskEvents' }, { label: '风险规则', operation: 'listRiskRules' }],
  '/admin/media': [{ label: '求片队列', operation: 'listMediaRequests' }, { label: '影片目录', operation: 'listMediaCatalog' }, { label: 'MoviePilot 任务', operation: 'listMoviePilotJobs' }],
  '/admin/support': [{ label: '工单队列', operation: 'listTickets' }, { label: '影评审核', operation: 'listReviewsForModeration' }],
  '/admin/engagement': [{ label: '广播任务', operation: 'listBroadcasts' }, { label: '自动化规则', operation: 'listAutomationRules' }, { label: '执行记录', operation: 'listAutomationExecutions' }],
  '/admin/system': [{ label: '动态设置', operation: 'listDynamicSettings' }, { label: '凭据元数据', operation: 'listCredentialMetadata' }, { label: '角色', operation: 'listRoles' }, { label: '权限', operation: 'listPermissions' }, { label: 'API 客户端', operation: 'listAPIClients' }, { label: '操作审计', operation: 'listAuditLogs' }],
}

const text = (key: string, label: string, placeholder = '', required = true): ActionField => ({ key, label, placeholder, required })
export const actions: Record<string, PageAction[]> = {
  '/emby': [{ label: '开通 Emby', title: '申请开通站点账号', operation: 'requestEmbyProvisioning', idempotent: true, fields: [text('username', 'Emby 用户名'), text('invitation_code', '邀请码', '管理员生成的邀请码')] }, { label: '认领账号', title: '认领已有 Emby 账号', operation: 'claimImportedEmbyUser', fields: [text('token', '认领令牌')] }],
  '/wallet': [{ label: '创建充值订单', title: '选择充值商品', operation: 'createRechargeOrder', idempotent: true, fields: [text('product_id', '充值商品 ID'), text('provider', '支付渠道')] }, { label: '购买会员', title: '使用积分购买会员', operation: 'purchaseMembershipWithWallet', idempotent: true, fields: [text('product_id', '会员商品 ID')] }],
  '/tickets': [{ label: '新建工单', title: '创建服务工单', operation: 'createTicket', fields: [text('subject', '主题'), { key: 'category', label: '分类', type: 'select', options: [{ label: '一般问题', value: 'general' }, { label: '账号问题', value: 'account' }, { label: '播放问题', value: 'playback' }] }, { key: 'priority', label: '优先级', type: 'select', options: [{ label: '普通', value: 'normal' }, { label: '较高', value: 'high' }] }, { key: 'body', label: '问题描述', type: 'textarea', required: true }], defaults: { category: 'general', priority: 'normal' } }, { label: '回复工单', title: '回复已有工单', operation: 'replyToMyTicket', fields: [{ ...text('id', '工单 ID'), path: true }, { key: 'body', label: '回复内容', type: 'textarea', required: true }] }],
  '/reviews': [{ label: '发布影评', title: '发布影片评价', operation: 'submitReview', fields: [text('media_id', '影片 ID'), { key: 'rating', label: '评分（1-10）', type: 'number', required: true }, text('title', '标题'), { key: 'body', label: '正文', type: 'textarea', required: true }, { key: 'contains_spoilers', label: '包含剧透', type: 'checkbox' }] }],
  '/account': [{ label: '绑定 Telegram', title: '生成 Telegram 绑定码', operation: 'createTelegramLinkRequest', fields: [] }],
  '/notifications': [{ label: '标记已读', title: '标记通知为已读', operation: 'markNotificationRead', fields: [{ ...text('id', '通知 ID'), path: true }] }, { label: '设置通知偏好', title: '修改通知渠道', operation: 'setNotificationPreference', fields: [{ ...text('event', '事件标识'), path: true }, { ...text('channel', '渠道'), path: true }, { key: 'enabled', label: '启用', type: 'checkbox' }] }],
  '/admin/accounts': [{ label: '调整账号状态', title: '账号生命周期', operation: 'changeAccountLifecycle', permission: 'accounts.lifecycle', fields: [{ ...text('id', '账号 ID'), path: true }, { key: 'status', label: '目标状态', type: 'select', options: [{ label: '启用', value: 'active' }, { label: '暂停', value: 'suspended' }, { label: '关闭', value: 'closed' }] }, text('reason', '原因')] }],
  '/admin/memberships': [{ label: '生成邀请码', title: '批量生成邀请码', operation: 'generateInvitations', permission: 'invitations.write', fields: [text('plan_id', '会员方案 ID'), { key: 'kind', label: '类型', type: 'select', options: [{ label: '注册邀请码', value: 'registration' }, { label: '续费邀请码', value: 'renewal' }] }, { key: 'count', label: '生成数量', type: 'number' }, { key: 'max_uses', label: '每码可用次数', type: 'number' }], defaults: { kind: 'registration', count: 1, max_uses: 1 } }],
  '/admin/emby': [{ label: '添加实例', title: '添加 Emby 实例', operation: 'createEmbyInstance', permission: 'emby_instances.write', fields: [text('name', '实例名称'), text('base_url', '服务地址', 'http://emby:8096'), text('credential_name', '凭据名称'), { key: 'enabled', label: '启用', type: 'checkbox' }, { key: 'is_default', label: '默认实例', type: 'checkbox' }, { key: 'verify_tls', label: '验证 TLS', type: 'checkbox' }, { key: 'priority', label: '优先级', type: 'number' }], defaults: { enabled: true, verify_tls: true, priority: 100 } }],
  '/admin/batches': [{ label: '暂停任务', title: '暂停批量任务', operation: 'pauseBatchOperation', permission: 'batch_operations.write', fields: [{ ...text('id', '任务 ID'), path: true }] }, { label: '恢复任务', title: '恢复批量任务', operation: 'resumeBatchOperation', permission: 'batch_operations.write', fields: [{ ...text('id', '任务 ID'), path: true }] }, { label: '重试失败项', title: '重试批量任务失败项', operation: 'retryBatchOperation', permission: 'batch_operations.write', fields: [{ ...text('id', '任务 ID'), path: true }] }],
  '/admin/playback': [{ label: '新增设备规则', title: '客户端黑白名单规则', operation: 'createDeviceRule', permission: 'devices.write', fields: [text('name', '规则名称'), { key: 'decision', label: '名单决策', type: 'select', options: [{ label: '白名单（允许）', value: 'allow' }, { label: '黑名单（拒绝）', value: 'deny' }] }, { key: 'match_field', label: '匹配字段', type: 'select', options: [{ label: '客户端名称', value: 'client_name' }, { label: '设备名称', value: 'device_name' }] }, { key: 'match_operator', label: '匹配方式', type: 'select', options: [{ label: '精确', value: 'exact' }, { label: '包含', value: 'contains' }, { label: '正则', value: 'regex' }] }, text('match_value', '匹配内容'), text('action', '处置动作', 'none'), { key: 'observation_mode', label: '观察模式', type: 'checkbox' }, { key: 'enabled', label: '启用', type: 'checkbox' }, { key: 'priority', label: '优先级', type: 'number' }], defaults: { decision: 'allow', match_field: 'client_name', match_operator: 'exact', action: 'none', observation_mode: true, enabled: true, priority: 100 } }],
  '/admin/risk': [{ label: '新增风险规则', title: '创建风险规则', operation: 'createRiskRule', permission: 'risk.write', fields: [text('code', '规则代码'), text('name', '规则名称'), text('rule_type', '规则类型'), { key: 'condition', label: '条件（JSON）', type: 'json', required: true, placeholder: '{"threshold": 3}' }, { key: 'severity', label: '级别', type: 'select', options: [{ label: '低', value: 'low' }, { label: '中', value: 'medium' }, { label: '高', value: 'high' }, { label: '严重', value: 'critical' }] }, text('action', '处置动作', 'notify'), { key: 'observation_mode', label: '观察模式', type: 'checkbox' }, { key: 'enabled', label: '启用', type: 'checkbox' }, { key: 'cooldown_seconds', label: '冷却秒数', type: 'number' }], defaults: { condition: '{}', severity: 'medium', action: 'notify', observation_mode: true, enabled: true, cooldown_seconds: 300 } }, { label: '确认风险', title: '确认风险事件', operation: 'acknowledgeRiskEvent', permission: 'risk.write', fields: [{ ...text('id', '事件 ID'), path: true }, text('reason', '处理说明')] }, { label: '标记误判', title: '标记风险误判并撤销处置', operation: 'markRiskEventFalsePositive', permission: 'risk.write', fields: [{ ...text('id', '事件 ID'), path: true }, text('reason', '误判原因')] }],
  '/admin/media': [{ label: '更新求片状态', title: '处理求片请求', operation: 'updateMediaRequestStatus', permission: 'media_requests.write', fields: [{ ...text('id', '求片 ID'), path: true }, { key: 'status', label: '状态', type: 'select', options: [{ label: '已接受', value: 'approved' }, { label: '已拒绝', value: 'rejected' }, { label: '已完成', value: 'fulfilled' }] }, text('reason', '处理说明', '', false), { key: 'expected_revision', label: '当前版本', type: 'number', required: true }] }],
  '/admin/support': [{ label: '回复工单', title: '公开回复或内部备注', operation: 'addTicketMessage', permission: 'tickets.write', fields: [{ ...text('id', '工单 ID'), path: true }, { key: 'body', label: '内容', type: 'textarea', required: true }, { key: 'internal', label: '仅内部可见', type: 'checkbox' }] }, { label: '审核影评', title: '处理影评审核', operation: 'moderateReview', permission: 'reviews.write', fields: [{ ...text('id', '影评 ID'), path: true }, { key: 'status', label: '结果', type: 'select', options: [{ label: '通过', value: 'approved' }, { label: '拒绝', value: 'rejected' }] }, text('reason', '审核说明'), { key: 'expected_revision', label: '当前版本', type: 'number', required: true }] }],
  '/admin/engagement': [{ label: '新建广播', title: '发送批量通知', operation: 'createBroadcast', permission: 'broadcasts.write', idempotent: true, fields: [text('title', '标题'), { key: 'body', label: '正文', type: 'textarea', required: true }, text('event_key', '事件标识', 'broadcast.general'), { key: 'channel', label: '渠道', type: 'select', options: [{ label: '站内信', value: 'in_app' }, { label: 'Telegram', value: 'telegram' }] }], defaults: { event_key: 'broadcast.general', channel: 'in_app', target: { status: 'active' } } }],
  '/admin/system': [{ label: '修改动态设置', title: '更新系统设置', operation: 'updateDynamicSetting', permission: 'settings.write', fields: [{ ...text('key', '设置键'), path: true }, { key: 'value', label: '新值（JSON）', type: 'json', required: true, placeholder: '字符串请写成 "value"' }, { key: 'value_type', label: '值类型', type: 'select', options: [{ label: '字符串', value: 'string' }, { label: '布尔值', value: 'boolean' }, { label: '整数', value: 'integer' }, { label: 'JSON', value: 'json' }] }, { key: 'expected_revision', label: '当前版本', type: 'number', required: true }, text('reason', '修改原因')] , defaults: { value_type: 'string' } }],
}
