import type { OperationId } from './generated/client'

export type Dataset = { label: string; operation: OperationId; query?: Record<string, string | number>; permission?: string }
export type ActionField = { key: string; label: string; type?: 'text' | 'password' | 'number' | 'textarea' | 'json' | 'select' | 'checkbox'; placeholder?: string; options?: { label: string; value: string }[]; required?: boolean; path?: boolean }
export type PageAction = { label: string; title: string; operation: OperationId; permission?: string; fields: ActionField[]; defaults?: Record<string, unknown>; idempotent?: boolean }

export const datasets: Record<string, Dataset[]> = {
  '/emby': [{ label: '已绑定账号', operation: 'listMyEmbyBindings' }],
  '/access': [{ label: '我的权益', operation: 'listMyEntitlements' }, { label: '可用线路', operation: 'listAvailableLines' }],
  '/favorites': [{ label: 'Emby 收藏', operation: 'listMyFavorites' }],
  '/wallet': [{ label: '充值订单', operation: 'listMyRechargeOrders' }, { label: '积分账本', operation: 'listMyLedger' }, { label: '充值商品', operation: 'listPublicRechargeProducts' }, { label: '会员商品', operation: 'listPublicMembershipProducts' }],
  '/playback': [{ label: '播放历史', operation: 'listMyPlaybackHistory' }, { label: '在线播放', operation: 'listMyOnlinePlayback' }],
  '/devices': [{ label: '我的设备', operation: 'listMyDevices' }],
  '/tickets': [{ label: '我的工单', operation: 'listMyTickets' }],
  '/reviews': [{ label: '我的影评', operation: 'listMyReviews' }, { label: '社区影评', operation: 'listPublicReviews' }],
  '/notifications': [{ label: '消息', operation: 'listMyNotifications' }, { label: '通知偏好', operation: 'listNotificationPreferences' }],
  '/account': [{ label: '账号资料', operation: 'getCurrentAccount' }],
  '/admin/accounts': [{ label: '统一账号', operation: 'listAccounts' }, { label: '账号标签', operation: 'listAccountTags' }],
  '/admin/memberships': [{ label: '会员方案', operation: 'listMembershipPlans' }, { label: '邀请码', operation: 'listInvitations' }, { label: '会员商品', operation: 'listAllMembershipProducts' }],
  '/admin/emby': [{ label: 'Emby 实例', operation: 'listEmbyInstances' }, { label: '同步任务', operation: 'listEmbyTasks' }, { label: '远端账号', operation: 'listImportedEmbyUsers' }, { label: '账号绑定', operation: 'listEmbyBindings' }],
  '/admin/access': [{ label: '账号权益', operation: 'listAccountEntitlements' }, { label: '权益码', operation: 'listEntitlementCodes' }],
  '/admin/lines': [{ label: '线路端点', operation: 'listLines' }],
  '/admin/commerce': [{ label: '充值订单', operation: 'listRechargeOrders' }, { label: '退款', operation: 'listRechargeRefunds' }, { label: '充值商品', operation: 'listAllRechargeProducts' }, { label: '会员商品', operation: 'listAllMembershipProducts' }],
  '/admin/batches': [{ label: '批量任务', operation: 'listBatchOperations' }, { label: '账号标签', operation: 'listAccountTags' }],
  '/admin/playback': [{ label: '在线播放', operation: 'listOnlinePlayback' }, { label: '播放历史', operation: 'listPlaybackHistory' }, { label: '设备画像', operation: 'listDeviceProfiles' }, { label: '设备规则', operation: 'listDeviceRules' }],
  '/admin/risk': [{ label: '风险事件', operation: 'listRiskEvents' }, { label: '风险规则', operation: 'listRiskRules' }],
  '/admin/media': [{ label: '求片队列', operation: 'listMediaRequests' }, { label: '影片目录', operation: 'listMediaCatalog' }, { label: 'MoviePilot 任务', operation: 'listMoviePilotJobs' }],
  '/admin/support': [{ label: '工单队列', operation: 'listTickets' }, { label: '影评审核', operation: 'listReviewsForModeration' }, { label: '影评举报', operation: 'listReviewReports' }],
  '/admin/engagement': [{ label: '广播任务', operation: 'listBroadcasts' }, { label: '自动化规则', operation: 'listAutomationRules' }, { label: '执行记录', operation: 'listAutomationExecutions' }],
  '/admin/system': [{ label: '动态设置', operation: 'listDynamicSettings' }, { label: '凭据元数据', operation: 'listCredentialMetadata' }, { label: '角色', operation: 'listRoles' }, { label: '权限', operation: 'listPermissions' }, { label: 'API 客户端', operation: 'listAPIClients' }, { label: '操作审计', operation: 'listAuditLogs' }],
  '/admin/integrations': [{ label: '联调记录', operation: 'listIntegrationProbes' }],
}

const text = (key: string, label: string, placeholder = '', required = true): ActionField => ({ key, label, placeholder, required })
export const actions: Record<string, PageAction[]> = {
  '/emby': [{ label: '开通 Emby', title: '申请开通站点账号', operation: 'requestEmbyProvisioning', idempotent: true, fields: [text('username', 'Emby 用户名'), text('invitation_code', '邀请码', '管理员生成的邀请码')] }, { label: '认领账号', title: '认领已有 Emby 账号', operation: 'claimImportedEmbyUser', fields: [text('token', '认领令牌')] }],
  '/access': [{ label: '兑换权益码', title: '兑换媒体库访问权益', operation: 'redeemEntitlementCode', fields: [text('code', '权益码')] }],
  '/favorites': [{ label: '同步收藏', title: '从 Emby 拉取收藏', operation: 'syncMyFavorites', fields: [text('binding_id', 'Emby 绑定 ID')] }, { label: '修改收藏', title: '添加或取消 Emby 收藏', operation: 'setMyFavorite', fields: [text('binding_id', 'Emby 绑定 ID'), text('remote_item_id', 'Emby 影片 ID'), text('title', '影片名称'), text('media_type', '影片类型', 'Movie', false), text('media_id', 'Sakura 影片 ID', '', false), { key: 'favorite', label: '收藏', type: 'checkbox' }], defaults: { favorite: true } }],
  '/wallet': [{ label: '创建充值订单', title: '选择充值商品', operation: 'createRechargeOrder', idempotent: true, fields: [text('product_id', '充值商品 ID'), text('provider', '支付渠道')] }, { label: '购买会员', title: '使用积分购买会员', operation: 'purchaseMembershipWithWallet', idempotent: true, fields: [text('product_id', '会员商品 ID')] }],
  '/tickets': [{ label: '新建工单', title: '创建服务工单', operation: 'createTicket', fields: [text('subject', '主题'), { key: 'category', label: '分类', type: 'select', options: [{ label: '一般问题', value: 'general' }, { label: '账号问题', value: 'account' }, { label: '播放问题', value: 'playback' }] }, { key: 'priority', label: '优先级', type: 'select', options: [{ label: '普通', value: 'normal' }, { label: '较高', value: 'high' }] }, { key: 'body', label: '问题描述', type: 'textarea', required: true }], defaults: { category: 'general', priority: 'normal' } }, { label: '回复工单', title: '回复已有工单', operation: 'replyToMyTicket', fields: [{ ...text('id', '工单 ID'), path: true }, { key: 'body', label: '回复内容', type: 'textarea', required: true }] }],
  '/reviews': [{ label: '发布影评', title: '发布影片评价', operation: 'submitReview', fields: [text('media_id', '影片 ID'), { key: 'rating', label: '评分（1-10）', type: 'number', required: true }, text('title', '标题'), { key: 'body', label: '正文', type: 'textarea', required: true }, { key: 'contains_spoilers', label: '包含剧透', type: 'checkbox' }] }, { label: '点赞/取消', title: '修改影评点赞状态', operation: 'setReviewLike', fields: [{ ...text('id', '影评 ID'), path: true }, { key: 'liked', label: '点赞', type: 'checkbox' }], defaults: { liked: true } }, { label: '举报影评', title: '提交影评举报', operation: 'reportReview', fields: [{ ...text('id', '影评 ID'), path: true }, { key: 'reason', label: '原因', type: 'select', options: [{ label: '垃圾内容', value: 'spam' }, { label: '辱骂攻击', value: 'abuse' }, { label: '未标剧透', value: 'spoiler' }, { label: '版权问题', value: 'copyright' }, { label: '其他', value: 'other' }] }, { key: 'detail', label: '补充说明', type: 'textarea' }], defaults: { reason: 'other' } }],
  '/account': [{ label: '绑定 Telegram', title: '生成 Telegram 绑定码', operation: 'createTelegramLinkRequest', fields: [] }],
  '/notifications': [{ label: '标记已读', title: '标记通知为已读', operation: 'markNotificationRead', fields: [{ ...text('id', '通知 ID'), path: true }] }, { label: '设置通知偏好', title: '修改通知渠道', operation: 'setNotificationPreference', fields: [{ ...text('event', '事件标识'), path: true }, { ...text('channel', '渠道'), path: true }, { key: 'enabled', label: '启用', type: 'checkbox' }] }],
  '/admin/accounts': [{ label: '调整账号状态', title: '账号生命周期', operation: 'changeAccountLifecycle', permission: 'accounts.lifecycle', fields: [{ ...text('id', '账号 ID'), path: true }, { key: 'status', label: '目标状态', type: 'select', options: [{ label: '启用', value: 'active' }, { label: '暂停', value: 'suspended' }, { label: '关闭', value: 'closed' }] }, text('reason', '原因')] }],
  '/admin/memberships': [{ label: '生成邀请码', title: '批量生成邀请码', operation: 'generateInvitations', permission: 'invitations.write', fields: [text('plan_id', '会员方案 ID'), { key: 'kind', label: '类型', type: 'select', options: [{ label: '注册邀请码', value: 'registration' }, { label: '续费邀请码', value: 'renewal' }] }, { key: 'count', label: '生成数量', type: 'number' }, { key: 'max_uses', label: '每码可用次数', type: 'number' }], defaults: { kind: 'registration', count: 1, max_uses: 1 } }],
  '/admin/emby': [{ label: '添加实例', title: '添加 Emby 实例', operation: 'createEmbyInstance', permission: 'emby_instances.write', fields: [text('name', '实例名称'), text('base_url', '服务地址', 'http://emby:8096'), text('credential_name', '凭据名称'), { key: 'enabled', label: '启用', type: 'checkbox' }, { key: 'is_default', label: '默认实例', type: 'checkbox' }, { key: 'verify_tls', label: '验证 TLS', type: 'checkbox' }, { key: 'priority', label: '优先级', type: 'number' }], defaults: { enabled: true, verify_tls: true, priority: 100 } }],
  '/admin/access': [{ label: '生成权益码', title: '批量生成媒体库权益码', operation: 'generateEntitlementCodes', permission: 'entitlements.write', fields: [text('instance_id', 'Emby 实例 ID', '', false), text('resource_kind', '资源类型', 'emby_library'), text('resource_key', 'Emby 媒体库 ID'), { key: 'duration_days', label: '有效天数', type: 'number', required: true }, { key: 'count', label: '生成数量', type: 'number', required: true }, { key: 'metadata', label: '备注元数据（JSON）', type: 'json' }], defaults: { resource_kind: 'emby_library', duration_days: 30, count: 1, metadata: {} } }, { label: '直接授权', title: '给账号授予媒体库权益', operation: 'grantAccountEntitlement', permission: 'entitlements.write', fields: [text('account_id', '账号 ID'), text('instance_id', 'Emby 实例 ID', '', false), text('resource_kind', '资源类型', 'emby_library'), text('resource_key', 'Emby 媒体库 ID'), { key: 'duration_days', label: '有效天数', type: 'number', required: true }], defaults: { resource_kind: 'emby_library', duration_days: 30 } }, { label: '撤销权益', title: '撤销账号权益并同步 Emby', operation: 'revokeAccountEntitlement', permission: 'entitlements.write', fields: [{ ...text('id', '权益 ID'), path: true }, text('reason', '撤销原因')] }],
  '/admin/lines': [{ label: '新增线路', title: '添加访问线路', operation: 'createLine', permission: 'lines.write', fields: [text('name', '线路名称'), text('base_url', '线路地址', 'https://emby.example.com'), text('region', '地区', '', false), text('carrier', '运营商', '', false), { key: 'audience', label: '适用对象', type: 'select', options: [{ label: '全部用户', value: 'all' }, { label: '会员', value: 'member' }, { label: '管理员', value: 'admin' }] }, { key: 'weight', label: '权重', type: 'number' }, { key: 'sort_order', label: '排序', type: 'number' }, { key: 'enabled', label: '启用', type: 'checkbox' }, { key: 'maintenance', label: '维护中', type: 'checkbox' }], defaults: { audience: 'all', weight: 100, sort_order: 0, enabled: true, maintenance: false } }, { label: '修改线路', title: '修改线路与维护状态', operation: 'updateLine', permission: 'lines.write', fields: [{ ...text('id', '线路 ID'), path: true }, text('name', '线路名称'), text('base_url', '线路地址'), text('region', '地区', '', false), text('carrier', '运营商', '', false), { key: 'audience', label: '适用对象', type: 'select', options: [{ label: '全部用户', value: 'all' }, { label: '会员', value: 'member' }, { label: '管理员', value: 'admin' }] }, { key: 'weight', label: '权重', type: 'number' }, { key: 'sort_order', label: '排序', type: 'number' }, { key: 'enabled', label: '启用', type: 'checkbox' }, { key: 'maintenance', label: '维护中', type: 'checkbox' }, { key: 'expected_revision', label: '当前版本', type: 'number', required: true }] }, { label: '探测线路', title: '执行实时线路探测', operation: 'probeLine', permission: 'lines.write', fields: [{ ...text('id', '线路 ID'), path: true }] }],
  '/admin/batches': [{ label: '暂停任务', title: '暂停批量任务', operation: 'pauseBatchOperation', permission: 'batch_operations.write', fields: [{ ...text('id', '任务 ID'), path: true }] }, { label: '恢复任务', title: '恢复批量任务', operation: 'resumeBatchOperation', permission: 'batch_operations.write', fields: [{ ...text('id', '任务 ID'), path: true }] }, { label: '重试失败项', title: '重试批量任务失败项', operation: 'retryBatchOperation', permission: 'batch_operations.write', fields: [{ ...text('id', '任务 ID'), path: true }] }],
  '/admin/playback': [{ label: '新增设备规则', title: '客户端黑白名单规则', operation: 'createDeviceRule', permission: 'devices.write', fields: [text('name', '规则名称'), { key: 'decision', label: '名单决策', type: 'select', options: [{ label: '白名单（允许）', value: 'allow' }, { label: '黑名单（拒绝）', value: 'deny' }] }, { key: 'match_field', label: '匹配字段', type: 'select', options: [{ label: '客户端名称', value: 'client_name' }, { label: '设备名称', value: 'device_name' }] }, { key: 'match_operator', label: '匹配方式', type: 'select', options: [{ label: '精确', value: 'exact' }, { label: '包含', value: 'contains' }, { label: '正则', value: 'regex' }] }, text('match_value', '匹配内容'), text('action', '处置动作', 'none'), { key: 'observation_mode', label: '观察模式', type: 'checkbox' }, { key: 'enabled', label: '启用', type: 'checkbox' }, { key: 'priority', label: '优先级', type: 'number' }], defaults: { decision: 'allow', match_field: 'client_name', match_operator: 'exact', action: 'none', observation_mode: true, enabled: true, priority: 100 } }],
  '/admin/risk': [{ label: '新增风险规则', title: '创建风险规则', operation: 'createRiskRule', permission: 'risk.write', fields: [text('code', '规则代码'), text('name', '规则名称'), text('rule_type', '规则类型'), { key: 'condition', label: '条件（JSON）', type: 'json', required: true, placeholder: '{"threshold": 3}' }, { key: 'severity', label: '级别', type: 'select', options: [{ label: '低', value: 'low' }, { label: '中', value: 'medium' }, { label: '高', value: 'high' }, { label: '严重', value: 'critical' }] }, text('action', '处置动作', 'notify'), { key: 'observation_mode', label: '观察模式', type: 'checkbox' }, { key: 'enabled', label: '启用', type: 'checkbox' }, { key: 'cooldown_seconds', label: '冷却秒数', type: 'number' }], defaults: { condition: '{}', severity: 'medium', action: 'notify', observation_mode: true, enabled: true, cooldown_seconds: 300 } }, { label: '确认风险', title: '确认风险事件', operation: 'acknowledgeRiskEvent', permission: 'risk.write', fields: [{ ...text('id', '事件 ID'), path: true }, text('reason', '处理说明')] }, { label: '标记误判', title: '标记风险误判并撤销处置', operation: 'markRiskEventFalsePositive', permission: 'risk.write', fields: [{ ...text('id', '事件 ID'), path: true }, text('reason', '误判原因')] }],
  '/admin/media': [{ label: '更新求片状态', title: '处理求片请求', operation: 'updateMediaRequestStatus', permission: 'media_requests.write', fields: [{ ...text('id', '求片 ID'), path: true }, { key: 'status', label: '状态', type: 'select', options: [{ label: '已接受', value: 'approved' }, { label: '已拒绝', value: 'rejected' }, { label: '已完成', value: 'fulfilled' }] }, text('reason', '处理说明', '', false), { key: 'expected_revision', label: '当前版本', type: 'number', required: true }] }],
  '/admin/support': [{ label: '回复工单', title: '公开回复或内部备注', operation: 'addTicketMessage', permission: 'tickets.write', fields: [{ ...text('id', '工单 ID'), path: true }, { key: 'body', label: '内容', type: 'textarea', required: true }, { key: 'internal', label: '仅内部可见', type: 'checkbox' }] }, { label: '审核影评', title: '处理影评审核', operation: 'moderateReview', permission: 'reviews.write', fields: [{ ...text('id', '影评 ID'), path: true }, { key: 'status', label: '结果', type: 'select', options: [{ label: '通过', value: 'approved' }, { label: '拒绝', value: 'rejected' }] }, text('reason', '审核说明'), { key: 'expected_revision', label: '当前版本', type: 'number', required: true }] }, { label: '处理举报', title: '解决或驳回影评举报', operation: 'resolveReviewReport', permission: 'reviews.write', fields: [{ ...text('id', '举报 ID'), path: true }, { key: 'status', label: '处理结果', type: 'select', options: [{ label: '已处理', value: 'resolved' }, { label: '已驳回', value: 'dismissed' }] }, { key: 'resolution', label: '处理说明', type: 'textarea', required: true }] }],
  '/admin/engagement': [{ label: '新建广播', title: '发送批量通知', operation: 'createBroadcast', permission: 'broadcasts.write', idempotent: true, fields: [text('title', '标题'), { key: 'body', label: '正文', type: 'textarea', required: true }, text('event_key', '事件标识', 'broadcast.general'), { key: 'channel', label: '渠道', type: 'select', options: [{ label: '站内信', value: 'in_app' }, { label: 'Telegram', value: 'telegram' }] }], defaults: { event_key: 'broadcast.general', channel: 'in_app', target: { status: 'active' } } }],
  '/admin/system': [{ label: '修改动态设置', title: '更新系统设置', operation: 'updateDynamicSetting', permission: 'settings.write', fields: [{ ...text('key', '设置键'), path: true }, { key: 'value', label: '新值（JSON）', type: 'json', required: true, placeholder: '字符串请写成 "value"' }, { key: 'value_type', label: '值类型', type: 'select', options: [{ label: '字符串', value: 'string' }, { label: '布尔值', value: 'boolean' }, { label: '整数', value: 'integer' }, { label: '对象', value: 'object' }, { label: '数组', value: 'array' }] }, { key: 'expected_revision', label: '当前版本', type: 'number', required: true }, text('reason', '修改原因')] , defaults: { value_type: 'string' } }],
  '/admin/integrations': [{ label: '探测 Emby', title: '真实联调 Emby 实例', operation: 'probeIntegration', permission: 'integrations.probe', fields: [{ ...text('integration', '集成类型'), path: true }, text('instance_id', 'Emby 实例 ID', '', false)], defaults: { integration: 'emby' } }, { label: '探测 TMDB', title: '真实联调 TMDB', operation: 'probeIntegration', permission: 'integrations.probe', fields: [{ ...text('integration', '集成类型'), path: true }], defaults: { integration: 'tmdb' } }, { label: '探测 MoviePilot', title: '真实联调 MoviePilot', operation: 'probeIntegration', permission: 'integrations.probe', fields: [{ ...text('integration', '集成类型'), path: true }], defaults: { integration: 'moviepilot' } }, { label: '探测 Telegram', title: '真实联调 Telegram Bot API', operation: 'probeIntegration', permission: 'integrations.probe', fields: [{ ...text('integration', '集成类型'), path: true }], defaults: { integration: 'telegram' } }],
}

const jsonField = (key: string, label: string, required = true): ActionField => ({ key, label, type: 'json', required })
const numberField = (key: string, label: string, required = true): ActionField => ({ key, label, type: 'number', required })
const pathField = (key: string, label: string): ActionField => ({ ...text(key, label), path: true })
const appendActions = (route: string, items: PageAction[]) => { actions[route] = [...(actions[route] || []), ...items] }

appendActions('/admin/accounts', [
  { label: '分配角色', title: '分配账号角色', operation: 'assignAccountRoles', permission: 'roles.write', fields: [pathField('id', '账号 ID'), jsonField('roles', '角色代码（JSON 数组）')], defaults: { roles: [] } },
  { label: '分配会员', title: '为账号分配会员方案', operation: 'assignMembership', permission: 'memberships.write', fields: [pathField('id', '账号 ID'), text('plan_id', '会员方案 ID'), numberField('duration_days', '有效天数'), text('source_ref', '来源备注', 'web-admin', false)] },
  { label: '调整钱包', title: '通过不可变账本调整余额', operation: 'adjustAccountWallet', permission: 'wallets.adjust', idempotent: true, fields: [pathField('id', '账号 ID'), numberField('amount', '变动金额（可为负数）'), text('currency', '币种', 'POINTS'), text('reason', '调整原因')], defaults: { currency: 'POINTS' } },
])

appendActions('/admin/memberships', [
  { label: '新建会员方案', title: '创建会员方案', operation: 'createMembershipPlan', permission: 'memberships.write', fields: [text('code', '方案代码'), text('name', '方案名称'), text('description', '说明', '', false), numberField('duration_days', '默认天数'), jsonField('entitlements', '权益配置（JSON 对象）'), { key: 'enabled', label: '启用', type: 'checkbox' }, { key: 'is_default', label: '默认方案', type: 'checkbox' }, numberField('sort_order', '排序')], defaults: { entitlements: {}, enabled: true, is_default: false, sort_order: 0 } },
  { label: '更新会员方案', title: '更新会员方案', operation: 'updateMembershipPlan', permission: 'memberships.write', fields: [pathField('id', '方案 ID'), text('code', '方案代码'), text('name', '方案名称'), text('description', '说明', '', false), numberField('duration_days', '默认天数'), jsonField('entitlements', '权益配置（JSON 对象）'), { key: 'enabled', label: '启用', type: 'checkbox' }, { key: 'is_default', label: '默认方案', type: 'checkbox' }, numberField('sort_order', '排序'), numberField('expected_revision', '当前版本')], defaults: { entitlements: {}, enabled: true, is_default: false, sort_order: 0 } },
  { label: '撤销邀请码', title: '撤销尚未使用的邀请码', operation: 'revokeInvitation', permission: 'invitations.write', fields: [pathField('id', '邀请码 ID')] },
])

appendActions('/admin/emby', [
  { label: '更新实例', title: '更新 Emby 实例', operation: 'updateEmbyInstance', permission: 'emby_instances.write', fields: [pathField('id', '实例 ID'), text('name', '实例名称'), text('base_url', '服务地址'), text('credential_name', '凭据名称'), { key: 'enabled', label: '启用', type: 'checkbox' }, { key: 'is_default', label: '默认实例', type: 'checkbox' }, { key: 'verify_tls', label: '验证 TLS', type: 'checkbox' }, numberField('priority', '优先级'), numberField('expected_revision', '当前版本')] },
  { label: '启动同步', title: '创建 Emby 同步或对账任务', operation: 'enqueueEmbyInstanceTask', permission: 'emby_sync.write', idempotent: true, fields: [pathField('id', '实例 ID'), { key: 'type', label: '任务类型', type: 'select', options: [{ label: '同步账号', value: 'sync' }, { label: '远端对账', value: 'reconcile' }, { label: '导入用户', value: 'import' }, { label: '同步播放', value: 'playback_sync' }] }], defaults: { type: 'sync' } },
  { label: '重试任务', title: '重试失败的 Emby 任务', operation: 'retryEmbyTask', permission: 'emby_sync.write', fields: [pathField('id', '任务 ID')] },
  { label: '生成认领令牌', title: '为远端 Emby 用户生成认领令牌', operation: 'createEmbyClaimToken', permission: 'emby_bindings.write', fields: [pathField('id', '远端用户 ID'), numberField('expires_seconds', '有效秒数')], defaults: { expires_seconds: 900 } },
  { label: '管理员认领', title: '将远端 Emby 用户绑定到统一账号', operation: 'adminClaimEmbyUser', permission: 'emby_bindings.write', fields: [pathField('id', '远端用户 ID'), text('account_id', '统一账号 ID')] },
  { label: '收编旧身份', title: '将实例内旧身份转换为统一账号绑定', operation: 'adoptLegacyEmbyIdentities', permission: 'emby_bindings.write', fields: [pathField('id', '实例 ID')] },
])

appendActions('/admin/commerce', [
  { label: '新建充值商品', title: '创建充值商品', operation: 'createRechargeProduct', permission: 'commerce.products.write', fields: [text('code', '商品代码'), text('name', '商品名称'), text('description', '说明', '', false), numberField('price_minor', '支付金额（最小单位）'), text('payment_currency', '支付币种', 'CNY'), numberField('grant_amount', '到账积分'), text('wallet_currency', '钱包币种', 'POINTS'), { key: 'enabled', label: '启用', type: 'checkbox' }, numberField('sort_order', '排序')], defaults: { payment_currency: 'CNY', wallet_currency: 'POINTS', enabled: true, sort_order: 0 } },
  { label: '新建会员商品', title: '创建会员商品', operation: 'createMembershipProduct', permission: 'commerce.products.write', fields: [text('code', '商品代码'), text('name', '商品名称'), text('plan_id', '会员方案 ID'), numberField('duration_days', '有效天数'), numberField('price_amount', '钱包价格'), text('wallet_currency', '钱包币种', 'POINTS'), { key: 'enabled', label: '启用', type: 'checkbox' }, numberField('sort_order', '排序')], defaults: { wallet_currency: 'POINTS', enabled: true, sort_order: 0 } },
  { label: '更新充值商品', title: '更新充值商品', operation: 'updateRechargeProduct', permission: 'commerce.products.write', fields: [pathField('id', '商品 ID'), text('code', '商品代码'), text('name', '商品名称'), text('description', '说明', '', false), numberField('price_minor', '支付金额（最小单位）'), text('payment_currency', '支付币种'), numberField('grant_amount', '到账积分'), text('wallet_currency', '钱包币种'), { key: 'enabled', label: '启用', type: 'checkbox' }, numberField('sort_order', '排序'), numberField('expected_revision', '当前版本')] },
  { label: '更新会员商品', title: '更新会员商品', operation: 'updateMembershipProduct', permission: 'commerce.products.write', fields: [pathField('id', '商品 ID'), text('code', '商品代码'), text('name', '商品名称'), text('plan_id', '会员方案 ID'), numberField('duration_days', '有效天数'), numberField('price_amount', '钱包价格'), text('wallet_currency', '钱包币种'), { key: 'enabled', label: '启用', type: 'checkbox' }, numberField('sort_order', '排序'), numberField('expected_revision', '当前版本')] },
  { label: '订单退款', title: '创建幂等退款', operation: 'refundRechargeOrder', permission: 'commerce.orders.write', idempotent: true, fields: [pathField('id', '充值订单 ID'), numberField('wallet_amount', '退回钱包金额'), numberField('external_amount_minor', '外部退款金额'), text('reason', '退款原因')] },
])

appendActions('/admin/batches', [
  { label: '新建账号标签', title: '创建批量运营标签', operation: 'createAccountTag', permission: 'account_tags.write', fields: [text('code', '标签代码'), text('name', '标签名称'), text('color', '颜色', '#8b5cf6'), text('description', '说明', '', false)], defaults: { color: '#8b5cf6' } },
  { label: '更新账号标签', title: '更新批量运营标签', operation: 'updateAccountTag', permission: 'account_tags.write', fields: [pathField('id', '标签 ID'), text('code', '标签代码'), text('name', '标签名称'), text('color', '颜色'), text('description', '说明', '', false)] },
  { label: '新建批量任务', title: '创建可暂停、重试的批量运营任务', operation: 'createBatchOperation', permission: 'batch_operations.write', idempotent: true, fields: [text('operation_type', '操作类型'), jsonField('target', '目标筛选（JSON）'), jsonField('payload', '操作参数（JSON）'), numberField('max_attempts', '最大重试次数')], defaults: { target: {}, payload: {}, max_attempts: 3 } },
  { label: '取消任务', title: '取消批量任务', operation: 'cancelBatchOperation', permission: 'batch_operations.write', fields: [pathField('id', '任务 ID')] },
])

appendActions('/admin/risk', [
  { label: '更新风险规则', title: '更新风险规则', operation: 'updateRiskRule', permission: 'risk.write', fields: [pathField('id', '规则 ID'), text('code', '规则代码'), text('name', '规则名称'), text('rule_type', '规则类型'), jsonField('condition', '条件（JSON 对象）'), { key: 'severity', label: '级别', type: 'select', options: [{ label: '低', value: 'low' }, { label: '中', value: 'medium' }, { label: '高', value: 'high' }, { label: '严重', value: 'critical' }] }, text('action', '处置动作', 'notify'), { key: 'observation_mode', label: '观察模式', type: 'checkbox' }, { key: 'enabled', label: '启用', type: 'checkbox' }, numberField('cooldown_seconds', '冷却秒数'), numberField('expected_revision', '当前版本')], defaults: { condition: {}, severity: 'medium', action: 'notify', observation_mode: true, enabled: true, cooldown_seconds: 300 } },
  { label: '解决风险', title: '关闭已处理的风险事件', operation: 'resolveRiskEvent', permission: 'risk.write', fields: [pathField('id', '事件 ID'), text('reason', '处理说明')] },
])

appendActions('/admin/playback', [
  { label: '更新设备规则', title: '更新客户端黑白名单规则', operation: 'updateDeviceRule', permission: 'devices.write', fields: [pathField('id', '规则 ID'), text('name', '规则名称'), { key: 'decision', label: '名单决策', type: 'select', options: [{ label: '白名单', value: 'allow' }, { label: '黑名单', value: 'deny' }] }, { key: 'match_field', label: '匹配字段', type: 'select', options: [{ label: '客户端名称', value: 'client_name' }, { label: '设备名称', value: 'device_name' }] }, { key: 'match_operator', label: '匹配方式', type: 'select', options: [{ label: '精确', value: 'exact' }, { label: '包含', value: 'contains' }, { label: '正则', value: 'regex' }] }, text('match_value', '匹配内容'), text('action', '处置动作', 'none'), { key: 'observation_mode', label: '观察模式', type: 'checkbox' }, { key: 'enabled', label: '启用', type: 'checkbox' }, numberField('priority', '优先级'), numberField('expected_revision', '当前版本')] },
])

appendActions('/admin/media', [
  { label: '刷新媒体匹配', title: '重新执行 TMDB 与 Emby 匹配', operation: 'refreshMediaMatches', permission: 'media.write', fields: [pathField('id', '影片 ID')] },
  { label: '提交 MoviePilot', title: '将匹配资源提交给 MoviePilot', operation: 'submitMoviePilotResource', permission: 'media_requests.write', idempotent: true, fields: [pathField('id', '求片 ID'), jsonField('resource', '下载资源（JSON 对象）')] },
])

appendActions('/admin/support', [
  { label: '更新工单', title: '更新工单状态、优先级和负责人', operation: 'updateTicket', permission: 'tickets.write', fields: [pathField('id', '工单 ID'), { key: 'status', label: '状态', type: 'select', options: [{ label: '处理中', value: 'in_progress' }, { label: '等待用户', value: 'waiting_user' }, { label: '已解决', value: 'resolved' }, { label: '已关闭', value: 'closed' }] }, { key: 'priority', label: '优先级', type: 'select', options: [{ label: '普通', value: 'normal' }, { label: '较高', value: 'high' }, { label: '紧急', value: 'urgent' }] }, text('assigned_to', '负责人账号 ID', '', false), numberField('expected_revision', '当前版本')], defaults: { status: 'in_progress', priority: 'normal' } },
])

appendActions('/admin/engagement', [
  { label: '新建自动化', title: '创建事件驱动自动化规则', operation: 'createAutomationRule', permission: 'automations.write', fields: [text('code', '规则代码'), text('name', '规则名称'), text('description', '说明', '', false), text('trigger_event', '触发事件'), jsonField('conditions', '触发条件（JSON 对象）'), jsonField('actions', '执行动作（JSON 数组）'), { key: 'enabled', label: '启用', type: 'checkbox' }, numberField('priority', '优先级')], defaults: { conditions: {}, actions: [], enabled: true, priority: 100 } },
  { label: '更新自动化', title: '更新事件驱动自动化规则', operation: 'updateAutomationRule', permission: 'automations.write', fields: [pathField('id', '规则 ID'), text('code', '规则代码'), text('name', '规则名称'), text('description', '说明', '', false), text('trigger_event', '触发事件'), jsonField('conditions', '触发条件（JSON 对象）'), jsonField('actions', '执行动作（JSON 数组）'), { key: 'enabled', label: '启用', type: 'checkbox' }, numberField('priority', '优先级'), numberField('expected_revision', '当前版本')] },
])

appendActions('/admin/system', [
  { label: '回滚设置', title: '回滚动态设置版本', operation: 'rollbackDynamicSetting', permission: 'settings.rollback', fields: [pathField('key', '设置键'), numberField('target_revision', '目标版本'), numberField('expected_revision', '当前版本'), text('reason', '回滚原因')] },
  { label: '保存角色', title: '创建或更新自定义角色', operation: 'saveCustomRole', permission: 'roles.write', fields: [pathField('code', '角色代码'), text('name', '角色名称'), jsonField('permissions', '权限代码（JSON 数组）')], defaults: { permissions: [] } },
  { label: '保存凭据', title: '加密保存外部服务凭据', operation: 'putCredential', permission: 'credentials.write', fields: [pathField('name', '凭据名称'), text('kind', '凭据类型'), { key: 'secret', label: '密钥', type: 'password', required: true }, jsonField('metadata', '元数据（JSON 对象）', false)], defaults: { metadata: {} } },
  { label: '删除凭据', title: '删除凭据', operation: 'deleteCredential', permission: 'credentials.write', fields: [pathField('name', '凭据名称')] },
  { label: '新建 API 客户端', title: '创建开放 API 客户端', operation: 'createAPIClient', permission: 'api_clients.write', fields: [text('name', '客户端名称'), jsonField('scopes', 'Scope（JSON 数组）')], defaults: { scopes: [] } },
  { label: '吊销 API 客户端', title: '吊销开放 API 客户端', operation: 'revokeAPIClient', permission: 'api_clients.write', fields: [pathField('id', '客户端 ID')] },
])
